controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: 'en'
        ru: 'ru'

kernel:
    resource: ../../src/Kernel.php
    type: annotation

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en
        permanent: true