controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: 'en'
        lv: 'lv'
        ru: 'ru'

controllers_api:
    resource: ../../src/Controller/Api
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en
        permanent: true